FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY ./app /app

RUN pip install fastapi uvicorn